### ISSUE TITLE
Error Response on receiving some client's JWS Client Assertion signed by other client's private key

### ISSUE THREAD

**Issue by tnorimat** [jsoss-sig/keycloak-fapi#12]
test module : `FAPIRWID2EnsureClientIdInTokenEndpointWithPrivateKeyAndMTLSHolderOfKey`

When the authz server(keycloak) receives some client's(say client2) JWS Client Assertion signed by other client's(say client1) private key, it returns 400 Bad Request / error="unauthorized_client".

`CheckTokenEndpointHttpStatus401` and `CheckErrorFromTokenEndpointResponseErrorInvalidClient` expects 401 Unauthorized / error="invalid_client"

In keycloak, `JWTClientAuthenticator` processes JWS Client Assertion. At first, it read "sub" as client_id (https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication) and searches the public key registered by this client identified by client_id, along with "kid" in JWS Client Assertion's JOSE Header.

In this case, keycloak looks into client2's public key store to find client1's public key, which leads to "not find".

**Comment by tnorimat** [comment]
The corresponding jira ticket is https://issues.redhat.com/browse/KEYCLOAK-15448 .

**Comment by VinodAnandan** [comment]
Merged 

https://github.com/keycloak/keycloak/pull/7391

**Comment by tnorimat** [comment]
I'll close issue due to corresponding PR being merged.
