### ISSUE TITLE
 OAuth2 Client Authentication in private_key_jwt : support ES256 or PS256

### ISSUE THREAD

**Issue by tnorimat** [jsoss-sig/keycloak-fapi#2]
FAPI-RW-ID2(Implementer's Draft ver 2) [5.2.2.  Authorization server](https://openid.net/specs/openid-financial-api-part-2-ID2.html#authorization-server) 14 states that an authorization server shall support at least either [MTLS]
[Section 2](https://tools.ietf.org/html/draft-ietf-oauth-mtls-14#section-2) or OIDC [9.  Client Authentication](https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication) private_key_jwt as OAuth2 Client Authentication

If supporting private_key_jwt, we need to consider that FAPI-RW-ID2 [8.6.  JWS algorithm considerations](https://openid.net/specs/openid-financial-api-part-2-ID2.html#jws-algorithm-considerations) 1 states that at least ES256 or PS256 shall be supported in private_key_jwt.

The current version of keycloak(6.0.0) has already supported private_key_jwt, but only supported RS256 in private_key_jwt.

**Comment by tnorimat** [comment]
CheckDiscEndpointTokenEndpointAuthSigningAlgValuesSupported checks whether "PS256" or "ES256" is included in "token_endpoint_auth_signing_alg_values_supported" claim Server Metadata.

When supporting ES256 or PS256 for private_key_jwt, it is also needed that "PS256" or "ES256" is included in "token_endpoint_auth_signing_alg_values_supported" claim Server Metadata.

**Comment by tnorimat** [comment]
keycloak-jira : https://issues.jboss.org/browse/KEYCLOAK-11251

**Comment by tnorimat** [comment]
Also, it needs to specify which signature algorithms are accepted because we need to consider that FAPI-RW-ID2 [8.6.  JWS algorithm considerations](https://openid.net/specs/openid-financial-api-part-2-ID2.html#jws-algorithm-considerations) 1 states that at least ES256 or PS256 shall be supported in private_key_jwt so that we need the configuration of only ES256 or PS256 is accepted.

**Comment by tnorimat** [comment]
Resolved on 8.0.0

**Comment by wadahiro** [comment]
I confirmed `CheckDiscEndpointTokenEndpointAuthSigningAlgValuesSupported` passed expectedly in this pull request: https://github.com/jsoss-sig/keycloak-fapi/pull/29

![image](https://user-images.githubusercontent.com/28739/83104981-c6714d80-a0f4-11ea-885a-76a766ab4d94.png)

**Comment by tnorimat** [comment]
@wadahiro Thanks!

**Comment by tnorimat** [comment]
The corresponding PR is https://github.com/keycloak/keycloak/pull/6414
