### ISSUE TITLE
How to cancel authentication by a user during authentication and authorization flow

### ISSUE THREAD

**Issue by tnorimat** [jsoss-sig/keycloak-fapi#24]
Test modules `FAPIRWID2UserRejectsAuthenticationWithMTLS` and `FAPIRWID2UserRejectsAuthenticationWithPrivateKeyAndMTLSHolderOfKey` requires cancellation of authentication by the user.

**Comment by wadahiro** [comment]
I found a solution. By enabling "Consent Required" in the client configuration, the user can cancel the authentication flow. I tried the test case with keycloak 10.0.1 and the latest conformance suite in this pull request: https://github.com/jsoss-sig/keycloak-fapi/pull/29

The results were all clear!! 🎉 

![image](https://user-images.githubusercontent.com/28739/83109681-c1b09780-a0fc-11ea-8a26-e2890e4c5194.png)

@tnorimat Please close this issue.

**Comment by tnorimat** [comment]
@wadahiro Great! I'll close this issue.
