### ISSUE TITLE
FAPI-RW-5.2.3-3: claims_parameter_supported must be: true

### ISSUE THREAD

**Issue by wadahiro** [jsoss-sig/keycloak-fapi#32]
The test module `CheckDiscEndpointClaimsParameterSupported` expects the discovery endpoint returns `claims_parameter_supported = true`. But keycloak returns `false`.

[FAPI-RW-5.2.3-3](https://openid.net/specs/openid-financial-api-part-2-ID2.html#rfc.section.5.2.3) describes the client shall request user authentication by requesting the `acr` claim as an essential claim. It means OP needs to support use of the `claims` parameter.
When OP supports the parameter, the discovery endpoint should return `claims_parameter_supported = true`.

**Comment by tnorimat** [comment]
related keycloak-jira ticket created : https://issues.jboss.org/browse/KEYCLOAK-14380

**Comment by tnorimat** [comment]
https://github.com/keycloak/keycloak/pull/7232
