### ISSUE TITLE
Write design document of keycloak's CIBA support

### ISSUE THREAD

**Issue by tnorimat** [jsoss-sig/keycloak-fapi#48]
Based on the prototype in https://github.com/jsoss-sig/keycloak-fapi/issues/47 , Write design document of keycloak's CIBA support, submit it to [keycloak-community](https://github.com/keycloak/keycloak-community) repository, and be merged.

**Comment by tnorimat** [comment]
merged https://github.com/keycloak/keycloak-community/pull/105
merged design document can be found in https://github.com/keycloak/keycloak-community/blob/master/design/client-initiated-backchannel-authentication-flow.md

**Comment by vanhoanHoang** [comment]
@tnorimat Does Keycloak not support PUSH mode yet please ?

**Comment by tnorimat** [comment]
@vanhoanHoang Unfortunately the current keycloak does not support CIBA push mode, only support poll and ping mode.
Are there any actual use cases where push mode is beneficial?
