### ISSUE TITLE
Resource Server related FAILURE : Content-type HTTP header

### ISSUE THREAD

**Issue by tnorimat** [jsoss-sig/keycloak-fapi#8]
EnsureResourceResponseContentTypeIsJsonUTF8 checks Content-type HTTP header from Resource Server.

To pass these tests, the resource server defined as "resourceUrl" in the config file needs to be configured to satisfy Content-type HTTP header related requirements (FAPI-R-6.2.1-9, 10).

These test should be omitted because the test plan is for the authorization server (keycloak), not the resource server.

**Comment by wadahiro** [comment]
Fixed in https://github.com/jsoss-sig/keycloak-fapi/commit/30502323ec018e41bf865a1128160f1acc5536b1.

**Comment by tnorimat** [comment]
@wadahiro Thank you. I've confirmed the fixed codes. I'll close this issue.
